# Generated by Django 5.2.6 on 2025-10-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioNet', '0002_rename_isbn_livro_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='BiblioNet.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='BiblioNet.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(),
        ),
    ]
